package docgen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func newTestTree() *cobra.Command {
	root := &cobra.Command{
		Use:   "bkt",
		Short: "Bitbucket CLI",
	}

	// Command group with subcommands
	pr := &cobra.Command{
		Use:   "pr",
		Short: "Manage pull requests",
		Long:  "Work with pull requests on Bitbucket.",
	}

	prList := &cobra.Command{
		Use:     "list",
		Aliases: []string{"ls"},
		Short:   "List pull requests",
		Long:    "List pull requests in a repository, optionally filtered by state.",
		Example: `  # List open pull requests
  bkt pr list --state OPEN

  # List your pull requests
  bkt pr list --mine`,
	}
	prList.Flags().String("state", "OPEN", "Filter by state")
	prList.Flags().Bool("mine", false, "Show your PRs")
	prList.Flags().Int("limit", 20, "Maximum results")

	prCreate := &cobra.Command{
		Use:   "create",
		Short: "Create a pull request",
		Long:  "Create a new pull request from a source branch to a target branch.",
	}
	prCreate.Flags().StringP("title", "t", "", "PR title")
	prCreate.Flags().String("source", "", "Source branch")
	prCreate.Flags().String("target", "", "Target branch")
	prCreate.Flags().BoolP("draft", "d", false, "Create as draft")

	// Nested subcommand group (pr task -> task list, task create)
	prTask := &cobra.Command{
		Use:   "task",
		Short: "Manage PR tasks",
		Long:  "Create and manage tasks on pull requests.",
	}
	prTaskList := &cobra.Command{
		Use:   "list <id>",
		Short: "List tasks on a PR",
	}
	prTaskCreate := &cobra.Command{
		Use:   "create <id>",
		Short: "Create a task on a PR",
	}
	prTaskCreate.Flags().String("text", "", "Task text")
	prTask.AddCommand(prTaskList, prTaskCreate)

	// DC-only subcommand
	prReaction := &cobra.Command{
		Use:   "reaction",
		Short: "Manage comment reactions (DC only)",
		Long:  "Add or remove emoji reactions on pull request comments.",
	}

	// Cloud-only subcommand
	prPipeline := &cobra.Command{
		Use:   "pipeline <id>",
		Short: "Show pipeline status for a PR (Cloud only)",
		Long:  "Show pipeline status for a pull request.",
	}

	pr.AddCommand(prList, prCreate, prTask, prReaction, prPipeline)

	// Root persistent flags (inherited by all commands)
	root.PersistentFlags().StringP("context", "c", "", "Active context name")
	root.PersistentFlags().Bool("json", false, "Output in JSON format")

	// Hidden command (should be excluded)
	hidden := &cobra.Command{
		Use:    "internal-debug",
		Short:  "Debug internals",
		Hidden: true,
	}

	// Standalone command (no subcommands)
	api := &cobra.Command{
		Use:   "api <path>",
		Short: "Make raw API requests",
		Long:  "Call Bitbucket REST APIs directly.",
		Example: `  # Get projects
  bkt api /rest/api/1.0/projects`,
	}
	api.Flags().StringP("method", "X", "", "HTTP method")

	root.AddCommand(pr, hidden, api)
	return root
}

func TestGenerateGroupFile(t *testing.T) {
	root := newTestTree()
	pr, _, _ := root.Find([]string{"pr"})

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", pr, true)
	got := buf.String()

	// Header
	if !strings.Contains(got, "<!-- auto-generated by cmd/docgen") {
		t.Error("missing auto-generated header")
	}

	// Title
	if !strings.Contains(got, "# bkt pr") {
		t.Error("missing title '# bkt pr'")
	}

	// Long description
	if !strings.Contains(got, "Work with pull requests on Bitbucket.") {
		t.Error("missing Long description")
	}

	// Usage block
	if !strings.Contains(got, "bkt pr <command>") {
		t.Error("missing usage block")
	}

	// Subcommand table
	if !strings.Contains(got, "| Subcommand |") {
		t.Error("missing subcommand table header")
	}
	if !strings.Contains(got, "[list](#bkt-pr-list)") {
		t.Error("missing list subcommand link")
	}
	if !strings.Contains(got, "[create](#bkt-pr-create)") {
		t.Error("missing create subcommand link")
	}

	// Alias
	if !strings.Contains(got, "**Alias:** `ls`") {
		t.Error("missing alias for list")
	}

	// Subcommand sections
	if !strings.Contains(got, "## bkt pr list") {
		t.Error("missing 'bkt pr list' section")
	}
	if !strings.Contains(got, "## bkt pr create") {
		t.Error("missing 'bkt pr create' section")
	}

	// Flags table
	if !strings.Contains(got, "| Flag |") {
		t.Error("missing flags table")
	}
	if !strings.Contains(got, "`--state`") {
		t.Error("missing --state flag")
	}
	if !strings.Contains(got, "`-t`") {
		t.Error("missing -t shorthand")
	}
	if !strings.Contains(got, "`--draft`") {
		t.Error("missing --draft flag")
	}

	// Example block
	if !strings.Contains(got, "bkt pr list --state OPEN") {
		t.Error("missing example content")
	}
}

func TestGenerateStandaloneFile(t *testing.T) {
	root := newTestTree()
	api, _, _ := root.Find([]string{"api"})

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", api, true)
	got := buf.String()

	if !strings.Contains(got, "# bkt api") {
		t.Error("missing title")
	}
	if !strings.Contains(got, "Call Bitbucket REST APIs directly.") {
		t.Error("missing Long description")
	}
	if !strings.Contains(got, "`--method`") {
		t.Error("missing --method flag")
	}
	if !strings.Contains(got, "bkt api /rest/api/1.0/projects") {
		t.Error("missing example")
	}
	// Standalone should NOT have subcommand table
	if strings.Contains(got, "| Subcommand |") {
		t.Error("standalone command should not have subcommand table")
	}
}

func TestStandaloneHeadingDepth(t *testing.T) {
	root := newTestTree()
	api, _, _ := root.Find([]string{"api"})

	// emitHeader=false simulates standalone inside other.md
	var buf strings.Builder
	writeGroupFile(&buf, "bkt", api, false)
	got := buf.String()

	// Title should be H2, not H1
	if strings.Contains(got, "\n# bkt api") {
		t.Error("standalone should use H2 title, not H1")
	}
	if !strings.Contains(got, "## bkt api") {
		t.Error("missing H2 title for standalone command")
	}

	// Usage should be H3
	if !strings.Contains(got, "### Usage") {
		t.Error("standalone Usage should be H3")
	}
	if strings.Contains(got, "\n## Usage") {
		t.Error("standalone Usage should not be H2")
	}

	// Flags should be H4
	if !strings.Contains(got, "#### Flags") {
		t.Error("standalone Flags should be H4")
	}
	if !strings.Contains(got, "#### Inherited Flags") {
		t.Error("standalone Inherited Flags should be H4")
	}
}

func TestHiddenCommandsExcluded(t *testing.T) {
	root := newTestTree()
	groups := collectGroups(root)

	for _, g := range groups {
		if g.Name() == "internal-debug" {
			t.Error("hidden command should be excluded")
		}
	}
}

func TestCollectGroups(t *testing.T) {
	root := newTestTree()
	groups := collectGroups(root)

	names := make(map[string]bool)
	for _, g := range groups {
		names[g.Name()] = true
	}

	if !names["pr"] {
		t.Error("expected pr group")
	}
	if !names["api"] {
		t.Error("expected api group")
	}
	if names["internal-debug"] {
		t.Error("hidden command should not appear")
	}
}

func TestNestedSubcommands(t *testing.T) {
	root := newTestTree()
	pr, _, _ := root.Find([]string{"pr"})

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", pr, true)
	got := buf.String()

	// Parent group "pr task" should appear
	if !strings.Contains(got, "## bkt pr task") {
		t.Error("missing 'bkt pr task' section")
	}

	// Nested children should be rendered
	if !strings.Contains(got, "## bkt pr task list") {
		t.Error("missing nested 'bkt pr task list' section")
	}
	if !strings.Contains(got, "## bkt pr task create") {
		t.Error("missing nested 'bkt pr task create' section")
	}

	// Nested child flags should appear
	if !strings.Contains(got, "`--text`") {
		t.Error("missing --text flag from nested task create")
	}
}

func TestInheritedFlags(t *testing.T) {
	root := newTestTree()
	pr, _, _ := root.Find([]string{"pr"})

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", pr, true)
	got := buf.String()

	// Inherited flags from root should appear
	if !strings.Contains(got, "### Inherited Flags") {
		t.Error("missing Inherited Flags section")
	}
	if !strings.Contains(got, "`--context`") {
		t.Error("missing inherited --context flag")
	}
	if !strings.Contains(got, "`--json`") {
		t.Error("missing inherited --json flag")
	}
}

func TestPlatformTag(t *testing.T) {
	tests := []struct {
		name  string
		short string
		long  string
		want  string
	}{
		{"dc only marker", "Manage tasks (DC only)", "Create tasks.", "*(DC)*"},
		{"cloud only marker", "List issues (Cloud only)", "List issues.", "*(Cloud)*"},
		{"no marker", "List repos", "List all repositories.", ""},
		{"dc in long but not short", "Show status", "Data Center only.", ""},
		{"cloud in long but not short", "Show pipeline", "Bitbucket Cloud only.", ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cmd := &cobra.Command{Use: "test", Short: tt.short, Long: tt.long}
			got := platformTag(cmd)
			if got != tt.want {
				t.Errorf("platformTag() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestPlatformTagInSubcommandTable(t *testing.T) {
	root := newTestTree()
	pr, _, _ := root.Find([]string{"pr"})

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", pr, true)
	got := buf.String()

	// DC-only subcommand should have *(DC)* badge (without redundant "(DC only)")
	if !strings.Contains(got, "Manage comment reactions *(DC)*") {
		t.Error("missing *(DC)* tag for reaction in subcommand table")
	}
	if strings.Contains(got, "(DC only) *(DC)*") {
		t.Error("platform suffix should be stripped to avoid redundancy with badge")
	}

	// Cloud-only subcommand should have *(Cloud)* badge
	if !strings.Contains(got, "Show pipeline status for a PR *(Cloud)*") {
		t.Error("missing *(Cloud)* tag for pipeline in subcommand table")
	}

	// Cross-platform subcommand should NOT have a tag
	if strings.Contains(got, "List pull requests *(") {
		t.Error("cross-platform command should not have a platform tag")
	}
}

func TestOutputOutsideSkillDir(t *testing.T) {
	root := newTestTree()
	outDir := filepath.Join(t.TempDir(), "rules")

	// No SKILL.md in parent — should succeed without error
	if err := GenerateAll(root, "bkt", outDir); err != nil {
		t.Fatalf("GenerateAll should succeed without SKILL.md: %v", err)
	}

	// Rule files should still be generated
	if _, err := os.Stat(filepath.Join(outDir, "pr.md")); err != nil {
		t.Error("expected pr.md even without SKILL.md")
	}
}

func TestGroupExamples(t *testing.T) {
	// Top-level group with Example
	group := &cobra.Command{
		Use:   "branch",
		Short: "Manage branches",
		Example: `  # List branches
  bkt branch list`,
	}
	group.AddCommand(&cobra.Command{Use: "list", Short: "List branches"})

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", group, true)
	got := buf.String()

	if !strings.Contains(got, "bkt branch list") {
		t.Error("group command Example should be rendered")
	}
}

func TestNestedGroupExamples(t *testing.T) {
	root := newTestTree()

	// Add Example to the nested task group in the test tree
	pr, _, _ := root.Find([]string{"pr"})
	for _, sub := range pr.Commands() {
		if sub.Name() == "task" {
			sub.Example = `  # List tasks on PR 42
  bkt pr task list 42`
		}
	}

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", pr, true)
	got := buf.String()

	if !strings.Contains(got, "bkt pr task list 42") {
		t.Error("nested group Example should be rendered")
	}
}

func TestFlagsHintWithInheritedOnly(t *testing.T) {
	root := &cobra.Command{Use: "bkt"}
	root.PersistentFlags().Bool("json", false, "JSON output")

	leaf := &cobra.Command{Use: "status", Short: "Show status"}
	root.AddCommand(leaf)

	got := formatUseLine("bkt", leaf)
	if !strings.Contains(got, "[flags]") {
		t.Errorf("expected [flags] for inherited-only command, got %q", got)
	}
}

func TestTrailingSlashOutDir(t *testing.T) {
	root := newTestTree()
	skillDir := t.TempDir()
	outDir := filepath.Join(skillDir, "rules") + "/" // trailing slash
	writeTestFile(t, filepath.Join(skillDir, "SKILL.md"), "# Test\n\n## References\n\n- old\n")

	if err := GenerateAll(root, "bkt", outDir); err != nil {
		t.Fatalf("GenerateAll with trailing slash: %v", err)
	}

	// SKILL.md should still be updated despite trailing slash
	content, _ := os.ReadFile(filepath.Join(skillDir, "SKILL.md"))
	if !strings.Contains(string(content), "[pr](rules/pr.md)") {
		t.Error("SKILL.md not updated when outDir has trailing slash")
	}
}

func TestCustomOutDirName(t *testing.T) {
	root := newTestTree()
	skillDir := t.TempDir()
	outDir := filepath.Join(skillDir, "generated")
	writeTestFile(t, filepath.Join(skillDir, "SKILL.md"), "# Test\n\n## References\n\n- old\n")

	if err := GenerateAll(root, "bkt", outDir); err != nil {
		t.Fatalf("GenerateAll with custom dir: %v", err)
	}

	// Links should use "generated/" not "rules/"
	content, _ := os.ReadFile(filepath.Join(skillDir, "SKILL.md"))
	if !strings.Contains(string(content), "[pr](generated/pr.md)") {
		t.Error("SKILL.md links should use actual directory name 'generated'")
	}
	if strings.Contains(string(content), "rules/pr.md") {
		t.Error("SKILL.md should not contain hardcoded 'rules/' path")
	}
}

func TestStaleFilesRemoved(t *testing.T) {
	root := newTestTree()
	skillDir := t.TempDir()
	outDir := filepath.Join(skillDir, "rules")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, filepath.Join(skillDir, "SKILL.md"), "# Test\n\n## References\n\n- old\n")

	// Plant a stale generated .md file (has auto-generated header)
	staleFile := filepath.Join(outDir, "old-command.md")
	writeTestFile(t, staleFile, "<!-- auto-generated by cmd/docgen — do not edit -->\n\n# stale")

	// Plant a hand-maintained .md file (no auto-generated header)
	manualFile := filepath.Join(outDir, "NOTES.md")
	writeTestFile(t, manualFile, "# Hand-maintained notes\n")

	if err := GenerateAll(root, "bkt", outDir); err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}

	// Stale generated file should be gone
	if _, err := os.Stat(staleFile); !os.IsNotExist(err) {
		t.Error("stale old-command.md should have been removed")
	}

	// Hand-maintained file should be preserved
	if _, err := os.Stat(manualFile); err != nil {
		t.Error("hand-maintained NOTES.md should be preserved")
	}

	// Fresh files should exist
	if _, err := os.Stat(filepath.Join(outDir, "pr.md")); err != nil {
		t.Error("pr.md should still be generated")
	}
}

func TestLongFallbackToShort(t *testing.T) {
	cmd := &cobra.Command{
		Use:   "simple",
		Short: "A simple command",
	}

	var buf strings.Builder
	writeGroupFile(&buf, "bkt", cmd, true)
	got := buf.String()

	if !strings.Contains(got, "A simple command") {
		t.Error("should fall back to Short when Long is empty")
	}
}

func TestUpdateSkillReferences(t *testing.T) {
	dir := t.TempDir()
	skillPath := filepath.Join(dir, "SKILL.md")

	original := `---
name: bkt
---

# Bitbucket CLI

Some content here.

## References

- **Full command reference**: See [references/commands.md](references/commands.md)
`
	writeTestFile(t, skillPath, original)

	rules := []ruleEntry{
		{File: "pr.md", Label: "pr", Desc: "Manage pull requests"},
		{File: "repo.md", Label: "repo", Desc: "Manage repositories"},
		{File: "other.md", Label: "other", Desc: "api"},
	}

	if err := updateSkillReferences(skillPath, rules, "rules"); err != nil {
		t.Fatalf("updateSkillReferences: %v", err)
	}

	content, _ := os.ReadFile(skillPath)
	got := string(content)

	// Hand-maintained content preserved
	if !strings.Contains(got, "# Bitbucket CLI") {
		t.Error("lost hand-maintained content")
	}
	if !strings.Contains(got, "Some content here.") {
		t.Error("lost hand-maintained body")
	}

	// Old reference removed
	if strings.Contains(got, "references/commands.md") {
		t.Error("old reference should be replaced")
	}

	// New references present
	if !strings.Contains(got, "[pr](rules/pr.md)") {
		t.Error("missing pr rule link")
	}
	if !strings.Contains(got, "[repo](rules/repo.md)") {
		t.Error("missing repo rule link")
	}
	if !strings.Contains(got, "[other](rules/other.md)") {
		t.Error("missing other rule link")
	}

	// Auto-generated markers
	if !strings.Contains(got, "auto-generated by cmd/docgen") {
		t.Error("missing auto-generated start marker")
	}
	if !strings.Contains(got, "<!-- end auto-generated -->") {
		t.Error("missing auto-generated end marker")
	}
}

func TestUpdateSkillReferencesPreservesFooter(t *testing.T) {
	dir := t.TempDir()
	skillPath := filepath.Join(dir, "SKILL.md")

	original := "# CLI\n\n## References\n\n" +
		"<!-- auto-generated by cmd/docgen — do not edit below this line -->\n\n" +
		"- [pr](rules/pr.md) — old\n\n" +
		"<!-- end auto-generated -->\n\n" +
		"## Footer\n\nThis should be preserved.\n"
	writeTestFile(t, skillPath, original)

	rules := []ruleEntry{
		{File: "pr.md", Label: "pr", Desc: "Manage pull requests"},
		{File: "repo.md", Label: "repo", Desc: "Manage repositories"},
	}

	if err := updateSkillReferences(skillPath, rules, "rules"); err != nil {
		t.Fatalf("updateSkillReferences: %v", err)
	}

	content, _ := os.ReadFile(skillPath)
	got := string(content)

	// New references present
	if !strings.Contains(got, "[repo](rules/repo.md)") {
		t.Error("missing updated repo link")
	}

	// Old stale reference gone
	if strings.Contains(got, "— old") {
		t.Error("stale reference should be replaced")
	}

	// Footer preserved
	if !strings.Contains(got, "## Footer") {
		t.Error("footer after end marker should be preserved")
	}
	if !strings.Contains(got, "This should be preserved.") {
		t.Error("footer content should be preserved")
	}
}

func TestGenerateAll(t *testing.T) {
	root := newTestTree()

	// GenerateAll expects SKILL.md at filepath.Dir(outDir)/SKILL.md
	skillDir := t.TempDir()
	outDir := filepath.Join(skillDir, "rules")
	writeTestFile(t, filepath.Join(skillDir, "SKILL.md"), "# Test\n\n## References\n\n- old\n")

	if err := GenerateAll(root, "bkt", outDir); err != nil {
		t.Fatalf("GenerateAll: %v", err)
	}

	// Check pr.md exists
	prFile := filepath.Join(outDir, "pr.md")
	if _, err := os.Stat(prFile); err != nil {
		t.Fatalf("expected pr.md: %v", err)
	}
	content, _ := os.ReadFile(prFile)
	if !strings.Contains(string(content), "# bkt pr") {
		t.Error("pr.md missing title")
	}

	// Check other.md exists (standalone commands grouped)
	otherFile := filepath.Join(outDir, "other.md")
	if _, err := os.Stat(otherFile); err != nil {
		t.Fatalf("expected other.md: %v", err)
	}
	content, _ = os.ReadFile(otherFile)
	if !strings.Contains(string(content), "# bkt api") {
		t.Error("other.md missing api section")
	}

	// Hidden command should not produce a file
	hiddenFile := filepath.Join(outDir, "internal-debug.md")
	if _, err := os.Stat(hiddenFile); !os.IsNotExist(err) {
		t.Error("hidden command should not produce a file")
	}

	// SKILL.md updated with rule links
	skillContent, _ := os.ReadFile(filepath.Join(skillDir, "SKILL.md"))
	skillStr := string(skillContent)
	if !strings.Contains(skillStr, "[pr](rules/pr.md)") {
		t.Error("SKILL.md missing pr rule link")
	}
	if !strings.Contains(skillStr, "[other](rules/other.md)") {
		t.Error("SKILL.md missing other rule link")
	}
	if strings.Contains(skillStr, "- old") {
		t.Error("SKILL.md should have replaced old references")
	}
}
