// Package docgen generates skill rule files from a Cobra command tree.
package docgen

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// GenerateAll writes one markdown rule file per top-level command group into
// outDir. Standalone commands (no subcommands) are grouped into other.md.
func GenerateAll(root *cobra.Command, binName, outDir string) error {
	outDir = filepath.Clean(outDir)
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	// Remove stale .md files from a previous run so renamed/deleted
	// commands don't linger in the output directory.
	if err := removeMarkdownFiles(outDir); err != nil {
		return err
	}

	groups := collectGroups(root)

	var standalones []*cobra.Command
	for _, cmd := range groups {
		if !cmd.HasSubCommands() {
			standalones = append(standalones, cmd)
			continue
		}
		path := filepath.Join(outDir, cmd.Name()+".md")
		if err := writeFile(path, binName, cmd); err != nil {
			return err
		}
	}

	if len(standalones) > 0 {
		path := filepath.Join(outDir, "other.md")
		if err := writeStandalonesFile(path, binName, standalones); err != nil {
			return err
		}
	}

	// Build list of generated rule files for SKILL.md update
	var ruleFiles []ruleEntry
	for _, cmd := range groups {
		if cmd.HasSubCommands() {
			desc := stripPlatformSuffix(cmd.Short)
			if tag := platformTag(cmd); tag != "" {
				desc += " " + tag
			}
			ruleFiles = append(ruleFiles, ruleEntry{
				File:  cmd.Name() + ".md",
				Label: cmd.Name(),
				Desc:  desc,
			})
		}
	}
	if len(standalones) > 0 {
		var names []string
		for _, cmd := range standalones {
			names = append(names, cmd.Name())
		}
		ruleFiles = append(ruleFiles, ruleEntry{
			File:  "other.md",
			Label: "other",
			Desc:  strings.Join(names, ", "),
		})
	}

	// Update SKILL.md references section (skip if SKILL.md doesn't exist,
	// e.g. when -o points outside the skill directory for preview).
	skillPath := filepath.Join(filepath.Dir(outDir), "SKILL.md")
	rulesDir := filepath.Base(outDir) // e.g. "rules" or "generated"
	if _, err := os.Stat(skillPath); err == nil {
		if err := updateSkillReferences(skillPath, ruleFiles, rulesDir); err != nil {
			return err
		}
	}

	return nil
}

type ruleEntry struct {
	File  string
	Label string
	Desc  string
}

// updateSkillReferences replaces the ## References section in SKILL.md with
// links to the generated rule files.
func updateSkillReferences(skillPath string, rules []ruleEntry, rulesDir string) error {
	data, err := os.ReadFile(skillPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", skillPath, err)
	}

	content := string(data)

	const startMarker = "<!-- auto-generated by cmd/docgen — do not edit below this line -->"
	const endMarker = "<!-- end auto-generated -->"

	// Build the new generated block
	var gen strings.Builder
	gen.WriteString(startMarker + "\n\n")
	for _, r := range rules {
		fmt.Fprintf(&gen, "- [%s](%s/%s) — %s\n", r.Label, rulesDir, r.File, r.Desc)
	}
	gen.WriteString("\n" + endMarker)

	// Try to replace an existing generated block (between start and end markers)
	startIdx := strings.Index(content, startMarker)
	endIdx := strings.Index(content, endMarker)
	if startIdx >= 0 && endIdx >= startIdx {
		content = content[:startIdx] + gen.String() + content[endIdx+len(endMarker):]
		return os.WriteFile(skillPath, []byte(content), 0o644)
	}

	// No existing generated block — find ## References and replace
	// everything from the heading to the next ## heading (or EOF)
	const refHeading = "## References"
	refIdx := strings.Index(content, refHeading)
	if refIdx >= 0 {
		// Find the next ## heading after References (if any) to preserve content after it
		after := content[refIdx+len(refHeading):]
		nextHeading := strings.Index(after, "\n## ")
		var tail string
		if nextHeading >= 0 {
			tail = after[nextHeading+1:] // keep the \n before ##
		}
		content = content[:refIdx] + refHeading + "\n\n" + gen.String() + "\n" + tail
	} else {
		// No References section — append one
		content = strings.TrimRight(content, "\n") + "\n\n" + refHeading + "\n\n" + gen.String() + "\n"
	}

	return os.WriteFile(skillPath, []byte(content), 0o644)
}

const generatedHeader = "<!-- auto-generated by cmd/docgen"

// removeMarkdownFiles deletes .md files in dir that were previously generated
// by docgen (identified by the auto-generated header comment). Hand-maintained
// files are left untouched.
func removeMarkdownFiles(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read output dir: %w", err)
	}
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".md" {
			continue
		}
		path := filepath.Join(dir, e.Name())
		head, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if !strings.HasPrefix(string(head), generatedHeader) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove stale file %s: %w", e.Name(), err)
		}
	}
	return nil
}

// collectGroups returns the visible top-level commands sorted by name.
func collectGroups(root *cobra.Command) []*cobra.Command {
	var cmds []*cobra.Command
	for _, cmd := range root.Commands() {
		if cmd.Hidden || cmd.Name() == "help" || cmd.Name() == "completion" {
			continue
		}
		cmds = append(cmds, cmd)
	}
	sort.Slice(cmds, func(i, j int) bool {
		return cmds[i].Name() < cmds[j].Name()
	})
	return cmds
}

func writeFile(path, binName string, cmd *cobra.Command) error {
	var buf strings.Builder
	writeGroupFile(&buf, binName, cmd, true)
	return writeMarkdownFile(path, buf.String())
}

func writeStandalonesFile(path, binName string, cmds []*cobra.Command) error {
	var buf strings.Builder

	fmt.Fprintln(&buf, "<!-- auto-generated by cmd/docgen — do not edit -->")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "# Other Commands")
	fmt.Fprintln(&buf)

	for i, cmd := range cmds {
		if i > 0 {
			fmt.Fprintln(&buf, "---")
			fmt.Fprintln(&buf)
		}
		writeGroupFile(&buf, binName, cmd, false)
	}
	return writeMarkdownFile(path, buf.String())
}

func writeMarkdownFile(path, content string) error {
	content = strings.TrimRight(content, "\n") + "\n"
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// heading returns a markdown heading prefix at the given depth (1 = "#", 2 = "##", etc.).
func heading(depth int) string {
	return strings.Repeat("#", depth)
}

// writeGroupFile writes a single command group (with its subcommands) to w.
// When emitHeader is true, the auto-generated comment is written at the top
// and headings start at H1. Otherwise headings shift down one level (for
// standalone commands inside other.md).
func writeGroupFile(w io.Writer, binName string, cmd *cobra.Command, emitHeader bool) {
	fullName := binName + " " + cmd.Name()

	// Base heading depth: H1 for top-level files, H2 inside other.md
	h1 := 1
	if !emitHeader {
		h1 = 2
	}

	if emitHeader {
		fmt.Fprintln(w, "<!-- auto-generated by cmd/docgen — do not edit -->")
		fmt.Fprintln(w)
	}

	// Title
	fmt.Fprintf(w, "%s %s\n\n", heading(h1), fullName)

	// Description
	desc := cmd.Long
	if desc == "" {
		desc = cmd.Short
	}
	if desc != "" {
		fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(desc))
	}

	// Usage
	if cmd.HasSubCommands() {
		fmt.Fprintf(w, "```\n%s <command> [flags]\n```\n\n", fullName)
	} else {
		useLine := formatUseLine(binName, cmd)
		fmt.Fprintf(w, "%s Usage\n\n```\n%s\n```\n\n", heading(h1+1), useLine)
	}

	// Leaf command — show flags and examples, then return
	if !cmd.HasSubCommands() {
		writeFlagsAtDepth(w, cmd, h1+2)
		writeExamplesAtDepth(w, cmd, h1+2)
		return
	}

	// Group command — show examples before subcommand table if present
	writeExamplesAtDepth(w, cmd, h1+2)

	// Subcommand table
	subs := visibleSubcommands(cmd)
	if len(subs) > 0 {
		fmt.Fprintf(w, "%s Subcommands\n\n", heading(h1+1))
		fmt.Fprintln(w, "| Subcommand | Description | Key Flags |")
		fmt.Fprintln(w, "|---|---|---|")
		for _, sub := range subs {
			anchor := strings.ReplaceAll(fullName+"-"+sub.Name(), " ", "-")
			keyFlags := topFlags(sub, 4)
			desc := stripPlatformSuffix(sub.Short)
			if tag := platformTag(sub); tag != "" {
				desc += " " + tag
			}
			fmt.Fprintf(w, "| [%s](#%s) | %s | %s |\n",
				sub.Name(), anchor, desc, keyFlags)
		}
		fmt.Fprintln(w)
	}

	// Per-subcommand sections
	for _, sub := range subs {
		writeSubcommandSection(w, fullName, sub)
	}
}

// writeSubcommandSection renders a subcommand. If the subcommand itself has
// children (e.g., "pr task" -> "pr task list", "pr task create"), it recurses.
func writeSubcommandSection(w io.Writer, parentPath string, sub *cobra.Command) {
	subFull := parentPath + " " + sub.Name()
	fmt.Fprintf(w, "## %s\n\n", subFull)

	subDesc := sub.Long
	if subDesc == "" {
		subDesc = sub.Short
	}
	if subDesc != "" {
		fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(subDesc))
	}

	// Aliases
	if len(sub.Aliases) > 0 {
		fmt.Fprintf(w, "**Alias:** `%s`\n\n", strings.Join(sub.Aliases, "`, `"))
	}

	// If this subcommand has its own children, render a mini subcommand table
	// and recurse into each child instead of showing usage/flags for the parent.
	nested := visibleSubcommands(sub)
	if len(nested) > 0 {
		fmt.Fprintf(w, "```\n%s <command> [flags]\n```\n\n", subFull)

		writeExamples(w, sub)

		fmt.Fprintln(w, "| Subcommand | Description |")
		fmt.Fprintln(w, "|---|---|")
		for _, child := range nested {
			fmt.Fprintf(w, "| %s | %s |\n", child.Name(), child.Short)
		}
		fmt.Fprintln(w)

		for _, child := range nested {
			writeSubcommandSection(w, subFull, child)
		}
		return
	}

	// Leaf subcommand — show usage, flags, examples
	subUseLine := formatUseLine(parentPath, sub)
	fmt.Fprintf(w, "### Usage\n\n```\n%s\n```\n\n", subUseLine)

	writeFlags(w, sub)
	writeExamples(w, sub)
}

func writeFlags(w io.Writer, cmd *cobra.Command) {
	writeFlagsAtDepth(w, cmd, 3)
}

func writeFlagsAtDepth(w io.Writer, cmd *cobra.Command, depth int) {
	local := collectFlags(cmd)
	inherited := collectInheritedFlags(cmd)

	if len(local) == 0 && len(inherited) == 0 {
		return
	}

	if len(local) > 0 {
		fmt.Fprintf(w, "%s Flags\n\n", heading(depth))
		writeFlagTable(w, local)
	}

	if len(inherited) > 0 {
		fmt.Fprintf(w, "%s Inherited Flags\n\n", heading(depth))
		writeFlagTable(w, inherited)
	}
}

func writeFlagTable(w io.Writer, flags []flagInfo) {
	fmt.Fprintln(w, "| Flag | Short | Description |")
	fmt.Fprintln(w, "|---|---|---|")
	for _, fl := range flags {
		short := ""
		if fl.Shorthand != "" {
			short = "`-" + fl.Shorthand + "`"
		}
		fmt.Fprintf(w, "| `--%s` | %s | %s |\n", fl.Name, short, fl.Usage)
	}
	fmt.Fprintln(w)
}

func writeExamples(w io.Writer, cmd *cobra.Command) {
	writeExamplesAtDepth(w, cmd, 3)
}

func writeExamplesAtDepth(w io.Writer, cmd *cobra.Command, depth int) {
	if cmd.Example == "" {
		return
	}
	fmt.Fprintf(w, "%s Examples\n\n", heading(depth))
	fmt.Fprintln(w, "```bash")
	fmt.Fprintln(w, strings.TrimSpace(cmd.Example))
	fmt.Fprintln(w, "```")
	fmt.Fprintln(w)
}

// formatUseLine builds a usage string like "bkt pr create [flags]".
// cmd.Use contains the command name plus args (e.g., "create" or "api <path>").
// parentPath is the already-qualified prefix (e.g., "bkt pr" or "bkt").
func formatUseLine(parentPath string, cmd *cobra.Command) string {
	// cmd.Use is "name <args>" — extract args portion after the command name
	parts := strings.SplitN(cmd.Use, " ", 2)
	args := ""
	if len(parts) > 1 {
		args = " " + parts[1]
	}
	// Append [flags] if the command accepts any flags (local or inherited)
	flags := ""
	if cmd.HasLocalFlags() || cmd.HasInheritedFlags() {
		flags = " [flags]"
	}
	return parentPath + " " + cmd.Name() + args + flags
}

// stripPlatformSuffix removes trailing "(DC only)" or "(Cloud only)" from a
// Short description so the generated table doesn't duplicate the badge.
func stripPlatformSuffix(s string) string {
	s = strings.TrimSuffix(s, " (DC only)")
	s = strings.TrimSuffix(s, " (Cloud only)")
	return s
}

// platformTag returns a markdown badge if the command is platform-specific.
// It checks for "(DC only)" or "(Cloud only)" markers in the Short field,
// which are the canonical source set in the Cobra command definitions.
func platformTag(cmd *cobra.Command) string {
	s := strings.ToLower(cmd.Short)
	if strings.Contains(s, "(dc only)") {
		return "*(DC)*"
	}
	if strings.Contains(s, "(cloud only)") {
		return "*(Cloud)*"
	}
	return ""
}

func visibleSubcommands(cmd *cobra.Command) []*cobra.Command {
	var subs []*cobra.Command
	for _, sub := range cmd.Commands() {
		if sub.Hidden || sub.Name() == "help" {
			continue
		}
		subs = append(subs, sub)
	}
	return subs
}

type flagInfo struct {
	Name      string
	Shorthand string
	Usage     string
}

func collectFlags(cmd *cobra.Command) []flagInfo {
	var flags []flagInfo
	cmd.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		flags = append(flags, flagInfo{
			Name:      f.Name,
			Shorthand: f.Shorthand,
			Usage:     f.Usage,
		})
	})
	return flags
}

func collectInheritedFlags(cmd *cobra.Command) []flagInfo {
	var flags []flagInfo
	cmd.InheritedFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		flags = append(flags, flagInfo{
			Name:      f.Name,
			Shorthand: f.Shorthand,
			Usage:     f.Usage,
		})
	})
	return flags
}

// topFlags returns the first n flag names formatted for the subcommand table.
func topFlags(cmd *cobra.Command, n int) string {
	flags := collectFlags(cmd)
	if len(flags) == 0 {
		return "—"
	}
	limit := n
	if len(flags) < limit {
		limit = len(flags)
	}
	var names []string
	for _, f := range flags[:limit] {
		names = append(names, "`--"+f.Name+"`")
	}
	return strings.Join(names, ", ")
}
