#!/usr/bin/env bash
# check-generated-skill.sh — verify generated skill rules are up-to-date.
# Runs the docgen generator into a temp dir and diffs against the committed
# rules. Exits non-zero if there's drift.
set -euo pipefail

GO="${GO:-go}"
RULES_DIR="skills/jk/rules"
SKILL_MD="skills/jk/SKILL.md"

# Generate into a temp directory
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Copy SKILL.md so the generator can update its References section
cp "$SKILL_MD" "$TMPDIR/SKILL.md"
mkdir -p "$TMPDIR/rules"

"$GO" run ./cmd/docgen -o "$TMPDIR/rules"

# Compare generated rule files (ignore manually authored files in RULES_DIR
# and trailing blank lines that end-of-file-fixer may strip)
STALE=""
for f in "$TMPDIR/rules"/*.md; do
    name="$(basename "$f")"
    if [ ! -f "$RULES_DIR/$name" ]; then
        STALE="${STALE}missing: $name\n"
    elif ! diff <(sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$RULES_DIR/$name") \
                 <(sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$f") >/dev/null 2>&1; then
        STALE="${STALE}differs: $name\n"
    fi
done

# Detect orphaned auto-generated files: committed files with the docgen header
# that the generator no longer emits.
for f in "$RULES_DIR"/*.md; do
    [ -f "$f" ] || continue
    name="$(basename "$f")"
    # Skip hand-maintained files (no auto-generated header)
    head -1 "$f" | grep -q '^<!-- auto-generated by cmd/docgen' || continue
    if [ ! -f "$TMPDIR/rules/$name" ]; then
        STALE="${STALE}orphaned: $name\n"
    fi
done

if [ -n "$STALE" ]; then
    echo "ERROR: Generated skill rules are stale. Run 'make generate-skill' and commit the result."
    printf "%b" "$STALE"
    exit 1
fi

# Compare the References section in SKILL.md
# Extract from the auto-generated marker to the end marker
extract_refs() {
    sed -n '/<!-- auto-generated by cmd\/docgen/,/<!-- end auto-generated -->/p' "$1"
}

COMMITTED_REFS="$(extract_refs "$SKILL_MD")"
GENERATED_REFS="$(extract_refs "$TMPDIR/SKILL.md")"

if [ "$COMMITTED_REFS" != "$GENERATED_REFS" ]; then
    echo "ERROR: SKILL.md References section is stale. Run 'make generate-skill' and commit the result."
    diff <(echo "$COMMITTED_REFS") <(echo "$GENERATED_REFS") || true
    exit 1
fi

echo "✓ Generated skill rules are up-to-date"
