services:
  flagembedding:
    build:
      context: .
      dockerfile: Dockerfile
    image: flagembedding-service:latest
    container_name: super-agent-flagembedding
    ports:
      - "31241:8001"
    environment:
      - FE_DEVICE=cuda
      - FE_EMBED_MODEL=/app/models/bge-m3
      - FE_RERANK_MODEL=/app/models/bge-reranker-v2-m3
      - FE_EMBED_DIM=1024
    volumes:
      - ./models:/app/models
    mem_limit: 32g
    cpus: "16"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "GPU-07f30641-8cc3-5853-29d7-7ccb43d17acf"
              capabilities: [ gpu ]

